name: Verify swinfo.json

on:
  push:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify KSP2 Mod
        uses: Rexicon226/VerifierAction@V0.5
